version: "3.11"
services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fast_api
    entrypoint: '/fastapi-entrypoint.sh'
    ports:
      - "${FASTAPI_PORT}:8080"
    volumes:
      - .:/app
    env_file:
      - .env/
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - "${MONGO_PORT}:27017"
    env_file:
      - .env/
    volumes:
      - ./data:/data/db

  kafka:
    image: bitnami/kafka
    ports:
      - "${KAFKA_PORT}:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${KAFKA_ADVERTISED_HOST_NAME}
      KAFKA_CREATE_TOPICS: ${KAFKA_CREATE_TOPICS}
      KAFKA_ZOOKEEPER_CONNECT: ${KAFKA_ZOOKEEPER_CONNECT}
      ALLOW_PLAINTEXT_LISTENER: ${ALLOW_PLAINTEXT_LISTENER}


  celery:
    build:
      dockerfile: Dockerfile
    entrypoint: '/celery-entrypoint.sh'
    env_file:
      - .env/
    volumes:
      - .:/app
    depends_on:
      - fastapi
      - redis

  redis:
    image: redis:alpine
    env_file:
      - .env/
    restart: always

  zookeeper:
    image: zookeeper
    ports:
      - "${ZOOKEEPER_PORT}:2181"






