name: Lint

on:
  push:
    branches:
    - dev
    - main
  pull_request:
    branches:
    - dev
    - main

jobs:
  Lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11.4
      uses: actions/setup-python@v1
      with:
        python-version: 3.11.4
    - name: Install pipenv
      run: |
        pip install pipenv
        pipenv install --system --deploy --ignore-pipfile
    - name: Run pre-commit
      run: |
        pipenv run pre-commit install
        pipenv run pre-commit run --all-files
